### ISSUE TITLE
Pipe to Mac Say example

### ISSUE THREAD

**Issue by hunter32292** [jessemillar/oob#3]
Hello Sir I am looking for a example using this command with the Mac `say` command, plz halp.

**Comment by jessemillar** [comment]
Not a bad idea. One moment.

**Comment by jessemillar** [comment]
Done. https://github.com/jessemillar/oob/commit/8298704c39c7292d1ef3a6f0ba2a1fbb7500dca2

**Comment by hunter32292** [comment]
This is Art.
![](https://i.giphy.com/media/l3q2LH45XElELRzRm/giphy.gif)
